// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_training/test/weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_training/data/api/weather_api.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WeatherAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherAPI extends _i1.Mock implements _i2.WeatherAPI {
  @override
  _i3.Future<String> fetchWeatherInfo({
    String? area = 'tokyo',
    DateTime? dateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWeatherInfo, [], {
              #area: area,
              #dateTime: dateTime,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#fetchWeatherInfo, [], {
                  #area: area,
                  #dateTime: dateTime,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#fetchWeatherInfo, [], {
                  #area: area,
                  #dateTime: dateTime,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  Map<String, String> toJson(({String area, DateTime dateTime})? value) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [value]),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);
}
